import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/styles.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h4>
          Contact
        </h4>

        <section className={styles.section2}>
          <div className={styles.me}>
            <h1 className={styles.metext}>
              PAUL
            </h1>
            <h1 className={styles.metext}>
              MISTERKA
            </h1>
            <img src="me.jpg" className={styles.hoverimg}/>
          </div>
        </section>
        
        <h1 className={styles.sectiontitle}>
          PROJECTS
        </h1>
        <h1 className={styles.sectiontitle}>
          BLOG
        </h1>

    
      </main>
    </div>
  )
}

export default Home
