import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/styles.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>paulmis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <div className={`${styles.me} ${styles.nowrap}`}>
          PA
          <span className={styles.bebas}>UL </span>
          MI
          <span className={styles.bebas}>STERKA</span>
        </div>
        <section className={styles.visual}>


        </section>
        <section className={styles.catalogs}>
          <section id='blog' className={styles.catalog}>
            <div className={styles.scrollWrapper}>
              <ul className={styles.catalogName}>
                <li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li>
              </ul>
              <ul className={styles.catalogName2}>
                <li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li><li>BLOG</li>
              </ul>
            </div>
            
            <ul className={styles.catalogWords}>
              <li>convince</li>
              <li>writing</li>
              <li>thoughts</li>
              <li>convey</li>
              <li>action</li>
              <li>meaning</li>
              <li>language</li>
            </ul>
          </section>
          <section id='projects' className={styles.catalog}>
            <ul className={styles.catalogName}>
              <li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li>
            </ul>
            <ul className={styles.catalogName2}>
              <li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li><li>PROJECTS</li>
            </ul>
            <ul className={styles.catalogWords}>
              <li>creative</li>
              <li>fun</li>
              <li>change</li>
              <li>interconnections</li>
              <li>people</li>
              <li>anger</li>
              <li>initiative</li>
            </ul>
          </section>
        </section>
      </main>
    </div>
  )
}

export default Home
